version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: keypo-wallet-db
    environment:
      POSTGRES_USER: keypo
      POSTGRES_PASSWORD: keypo_password
      POSTGRES_DB: keypo_wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: